language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
   allow_failures:
     - php: hhvm
     - php: 7.0

env:
  - JVERSION_TEST=3.4

branches:
  only:
    - development

install:
  - composer update

before_script:
  - mysql -e 'create database fof_test;'
  # - if [[ "$JVERSION_TEST" == "3.4" ]]; then cp Tests/environments/3.4/joomla.sql joomla.sql; fi
  # - mysql fof_test < joomla.sql
  - cp build/templates/include.php fof/include.php

after_script:
  - cat Tests/debug.txt

notifications:
  email: false

script: php vendor/phpunit/phpunit/phpunit --bootstrap=Tests/bootstrap.php Tests
