language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  include:
    - php: 5.3
      env: MOCKERY_VERSION = 0.9.4
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for PostgreSQL currently unsupported by HHVM
   allow_failures:
     - php: hhvm
     - php: 7.0

env:
  global:
    - JVERSION_TEST=3.4
  matrix:
    - DB=mysql
    - DB=pgsql

branches:
  only:
    - development

install:
  - composer update
  - if [ '$TRAVIS_PHP_VERSION' == '5.3' ]; then composer require mockery/mockery:${MOCKERY_VERSION}; fi

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database fof_test;'; fi
  - if [[ "$DB" == "mysql" ]]; then cp Tests/environments/"$JVERSION_TEST"/installation/sql/mysql/joomla.sql joomla.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql fof_test < joomla.sql; fi
  - if [[ "$DB" == "pgsql" ]]; then pgsql -e 'create database fof_test;'; fi
  - if [[ "$DB" == "pgsql" ]]; then cp Tests/environments/"$JVERSION_TEST"/installation/sql/postgresql/joomla.sql joomla.sql; fi
  - if [[ "$DB" == "pgsql" ]]; then pgsql fof_test < joomla.sql; fi
  - cp build/templates/include.php fof/include.php

after_script:
  - cat Tests/debug.txt

notifications:
  email: false

script: php vendor/phpunit/phpunit/phpunit --bootstrap=Tests/bootstrap.php Tests
