sudo: false
language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
     - php: hhvm
     - php: 7.0
     - php: 5.6
       env: JVERSION_TEST=3.5-dev
     - php: 5.5
       env: JVERSION_TEST=3.5-dev
     - php: 5.4
       env: JVERSION_TEST=3.5-dev
     - php: 5.3
       env: JVERSION_TEST=3.5-dev

env:
    - JVERSION_TEST=3.4
    - JVERSION_TEST=3.5-dev

branches:
  only:
    - development

install:
  - composer selfupdate
  - composer install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database fof_test;'; fi

after_script:
  - cat Tests/debug.txt

notifications:
  email: false

script: vendor/bin/phpunit -c phpunit.xml
